#:schema ./schema.json

[project]
name = "pixi-manifest-format"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ruben Arts <ruben.arts@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
generate = "python model.py > schema.json"
fmt = "ruff format model.py"
lint = "ruff check model.py --fix"
test = "pytest"

[dependencies]
pyyaml = ">=6.0.1,<6.1"
pydantic = ">=2.6.3,<2.7"
ruff = ">=0.3.0,<0.4"
pytest = ">=8.0.2,<8.1"
jsonschema = ">=4.21.1,<4.22"
python = ">=3.12.2,<3.13"
toml = ">=0.10.2,<0.11"
